### ISSUE TITLE
Erreur export bilan global

### ISSUE THREAD

**Issue by noelmartinon** [PnCevennes/gt_reservation_animations#82]
L'export conduit à une erreur 500. Dans les logs, j'ai : 
```
sqlalchemy.exc.ProgrammingError: (psycopg2.errors.UndefinedColumn) column v_export_bilans_global.categorie_annulation does not exist
LINE 1: ...te, animations.v_export_bilans_global.annulation, animations...
```
Après vérification, je me suis rendu compte que le champ 'categorie_annulation' n'existe pas dans la vue 'v_export_bilans_global'.

En exécutant de nouveau `sudo -u geotrek psql -d geotrekdb -f db/create_db_structure.sql`, j'ai cette erreur : 
`psql:db/create_db_structure.sql:207: ERROR:  cannot change name of view column "raison_annulation" to "categorie_annulation"`.

Quelqu'un aurait-il une solution pour corriger ce problème ?

**Comment by camillemonchicourt** [comment]
Sans avoir testé ni connaître le contexte, on dirait qu'il essaie de modifier une vue qui existe déjà.

Or il n'est pas possible de modifier les colonnes d'une vue existante. Il faut la supprimer au préalable et le recréer si on veut en modifier les colonnes.

**Comment by noelmartinon** [comment]
Mais oui, bien sûr ! Un DROP VIEW suivi de l'exécution du script SQL a reglé le problème.
Merci bien.
